#!/bin/sh

buildNumLeft=$(plutil -extract CFBundleShortVersionString raw -o - ./Resources/Info.plist)
buildNumRight=$(plutil -extract CFBundleVersion raw -o - ./Resources/Info.plist)

GPG_TTY=$(tty)

git add .
git commit -S -m "$buildNumLeft.$buildNumRight"
git push