#!/bin/sh

buildNum=$(plutil -extract CFBundleVersion raw -o - ./Resources/Info.plist)
incr=1
buildNum=`expr $buildNum + $incr`
plutil -replace CFBundleVersion -string "$buildNum" ./Resources/Info.plist
echo "**** BUILD ****"
./build
echo "**** SIGN ****"
./sign
echo "**** PUSH ****"
export GPG_TTY=$(tty)
git add .
git commit -S -m "build_$buildNum"
git push